### ISSUE TITLE
BaseSchema.sql missing some stored procedures

### ISSUE THREAD

**Issue by brendankowitz** [microsoft/healthcare-shared-components#48]
**Describe the bug**
The [BaseSchema.sql](https://github.com/microsoft/healthcare-shared-components/blob/master/src/Microsoft.Health.SqlServer/Features/Schema/Migrations/BaseSchema.sql) script is missing stored procedures for UpsertSchemaVersion and SelectCurrentSchemaVersion.

**Expected behavior**
The required base schema is installed

**Actual behavior**
```
Error from SQL database on upserting InstanceSchema information
System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'dbo.UpsertInstanceSchema'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader()
   at System.Data.SqlClient.SqlCommand.InternalEndExecuteReader(IAsyncResult asyncResult, String endMethod)
   at System.Data.SqlClient.SqlCommand.EndExecuteReaderInternal(IAsyncResult asyncResult)
```

**Comment by brendankowitz** [comment]
@rbans96 if this is completed/verified can you close this issue?
